### PR TITLE
first prototype : make the zone of information disappear, add a bar a…

### PR DESCRIPTION
**Pull request by Yifan-Zeng**
make the zone of information disappear,
make the main div bigger,
create a bar at right with a logo of help.
the capture of screen after modification ;
Capture d’écran 2021-05-27 à 17 22 36

### CODE REVIEW

**Comment by Yifan-Zeng** [comment]
PTAL (I don't know why the javascript part in poll.component.html doesn't work)

**Comment by Jogo27** [comment]
> I don't know why the javascript part in poll.component.html doesn't work

This is because an important principle of Angular is to separate HTML from JavaScript/TypeScript.

**Comment by Yifan-Zeng** [comment]
PTAL 
After changes, the bar now looks like this:
Capture d’écran 2021-06-01 à 18 23 41

**Comment by Jogo27** [comment]
I don't understand why the icon is lower now. I suggested to use `position: absolute` for the simplemenu, not for the icon. I don't understand why you have two levels of div (sidemenu and simplemenu). But these are implementation details. The prototype is almost done now. The only remaining thing is the space between the main part (the ballot) and the bar, which is much too large. The bar will expand over the main part and the user must guess that. I think that the position of the main part dhould looks like if there was no bar, and the bar should already appear to be over the main part, maybe using shadows.

**Comment by Jogo27** [comment]
It's nice! There are still some details that will have to be fixed (notably the shadow over the ballot), but here is was I got pretty fast
image
I think you can now close this ticket and start the second prototype with the bar opened.

**Pull request closed without merging**
