### PR TITLE
Adjust word split and line break on narrow screen

### PR DESCRIPTION
**Pull request by WanJIN0415**
PTAL #91 

The results are following : 
image
image

### CODE REVIEW

**Review by Jogo27 — CHANGES_REQUESTED** [review]
I would like to have something like
> Phobia, C. Hippopoto-
> monstrosesquippedia-
> liophobia.

Instead of

> Phobia, C.
> Hippopotomonstrosesquipp
> edialiophobia.

Have you tried [the hyphens CSS property](https://drafts.csswg.org/css-text-3/#propdef-hyphens)?

**Comment by WanJIN0415** [comment]
PTAL
I could use `hyphens: auto`, but it only supports Google Chrome, not Firefox or IE, and `word-break: break-word` or `word-break: break-all` don't work in this case, so I don't know how to make the long word follow the index. Is there any other better solution ?

Here is the result with Google Chrome : 
image

The result with Firefox ( **the horizontal scroll still exists**) : 
image

**Comment by Jogo27** [comment]
You're right that there are compatibility issues with `hyphens: auto`. But according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens) and my own tests, Firefox implements it correctly. What really matter is whether this feature is implemented by the browsers used by most people. According to all surveys (for instance [this one](https://gs.statcounter.com/browser-market-share/mobile/worldwide)), Chrome, Safari and Samsung Internet represents together roughly 90% of mobile browsers. Similarly, Chrome, Safari and Android together represent 90% of the tablets browsers. According to MDN, using both `-webkit-hyphens: auto` and `hyphens: auto` should enable automatic hyphenation on all these four browsers.

**Comment by WanJIN0415** [comment]
PTAL

In the description, the long word will start on a new line. Is this a problem ?
image

**Review by Jogo27 — APPROVED** [review]
This is far from perfect, but this looks nicer than without tirets.

**Pull request merged**
