### PR TITLE
centerlise the table for small screen

### PR DESCRIPTION
**Pull request by Yifan-Zeng**
Before the width of table was too wide (go beyond main-container) so that it is not at center, after the change, it is no bigger than main-container. So it is at the center for the screen with minimum width of 320px.
Capture d’écran 2021-06-25 à 14 25 38

### CODE REVIEW

**Comment by Jogo27** [comment]
It is still not centered. In the following screenshot, you can easily see that the form does not fit in div.main-container.
image
You could of course further reduce the width of the form, but there is a better solution that ensures you that the form is always centered while not reducing the width of the form on larger screens.

**Comment by Yifan-Zeng** [comment]
PTAL

**Review by Jogo27 — CHANGES_REQUESTED** [review]
It's very complicated, not totally accurate (the border size is missing), and it doesn't respect the margins of all the other pages. Could you improve that?

**Comment by Yifan-Zeng** [comment]
PTAL

**Review by Jogo27 — APPROVED** [review]
Still complicated...

**Pull request merged**
